import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Terms & Conditions | FinanceHub",
    description: "Read the Terms and Conditions for using FinanceHub's free online financial calculator tools.",
};

export default function TermsPage() {
    const sectionStyle = { marginBottom: "2rem", color: "var(--secondary-foreground)", lineHeight: "1.8" };
    const headingStyle = { fontSize: "1.25rem", marginBottom: "0.75rem", color: "var(--foreground)" };

    return (
        <div style={{ maxWidth: "800px", margin: "2rem auto" }}>
            <h1 style={{ fontSize: "2.5rem", fontWeight: 800, marginBottom: "0.5rem" }}>
                <span className="gradient-text">Terms</span> & Conditions
            </h1>
            <p style={{ color: "var(--secondary-foreground)", marginBottom: "2.5rem" }}>Last Updated: February 21, 2026</p>

            <section style={sectionStyle}>
                <h2 style={headingStyle}>1. Acceptance of Terms</h2>
                <p>By accessing and using FinanceHub ("the Website"), you accept and agree to be bound by the terms and provisions of this agreement. If you do not agree to abide by these terms, please do not use this website.</p>
            </section>

            <section style={sectionStyle}>
                <h2 style={headingStyle}>2. Purpose of the Website</h2>
                <p>FinanceHub provides free, browser-based financial calculation tools for informational and educational purposes only. The calculators are designed to assist with personal finance planning, including SIP, EMI, GST, Income Tax, FD, PPF, CAGR, Lumpsum, and Salary Hike calculations.</p>
            </section>

            <section style={sectionStyle}>
                <h2 style={headingStyle}>3. No Professional Financial Advice</h2>
                <p>The content and tools on this website do <strong>not</strong> constitute professional financial, investment, tax, or legal advice. All results generated by our calculators are estimates based on the inputs you provide and standard mathematical formulas. We strongly recommend consulting a certified Chartered Accountant (CA), financial planner, or tax advisor before making any financial decisions.</p>
            </section>

            <section style={sectionStyle}>
                <h2 style={headingStyle}>4. Accuracy of Calculations</h2>
                <p>While we strive to keep the calculation formulas accurate and up to date with the latest government policies. We do not guarantee the accuracy, completeness, or reliability of any calculations. Tax slabs, interest rates, and government policies are subject to change without notice.</p>
            </section>

            <section style={sectionStyle}>
                <h2 style={headingStyle}>5. Intellectual Property</h2>
                <p>All content, design, graphics, and code on this website are the intellectual property of FinanceHub and are protected under applicable copyright laws. You may not reproduce, distribute, or create derivative works from the content without our express written permission.</p>
            </section>

            <section style={sectionStyle}>
                <h2 style={headingStyle}>6. Limitation of Liability</h2>
                <p>FinanceHub shall not be held liable for any losses or damages arising directly or indirectly from the use of this website, including but not limited to financial losses, investment decisions, or tax filing errors based on the results of our calculators.</p>
            </section>

            <section style={sectionStyle}>
                <h2 style={headingStyle}>7. Third-Party Advertisements</h2>
                <p>This website may display third-party advertisements served by Google AdSense or other advertising networks. We are not responsible for the content of these advertisements, and clicking on them is at your own risk.</p>
            </section>

            <section style={sectionStyle}>
                <h2 style={headingStyle}>8. Changes to Terms</h2>
                <p>We reserve the right to modify these Terms & Conditions at any time. Changes will be effective immediately upon posting on this page. Your continued use of the website following the posting of changes constitutes your acceptance of such changes.</p>
            </section>

            <section style={sectionStyle}>
                <h2 style={headingStyle}>9. Contact</h2>
                <p>For any questions regarding these Terms & Conditions, please reach out at: <strong>contact@financehub.com</strong></p>
            </section>
        </div>
    );
}
